import "./globals.css"
import { inter } from "@/app/fonts"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={inter.variable}>
      <body className="min-h-screen flex items-start pt-32">
        <div className="container mx-auto">{children}</div>
      </body>
    </html>
  )
}
